language: node_js

node_js:
   - "0.10"

before_install:
    - "sudo apt-get install cimg-dev libphash0-dev libmagickcore-dev"
    - npm install -g npm

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  - CXX=g++-4.8

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
